# Generated by Django 5.1.5 on 2025-03-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, default='STU7579', max_length=50, null=True),
        ),
    ]
